name: ble_bootstrap_channel
description: Transmit metadata between devices through Bluetooth Low Energy.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bluetooth_low_energy: ^4.0.0
  flutter:
    sdk: flutter
  venice_core:
    git: https://github.com/Venice-D2D/venice_core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
